title: "My Blog"
description: "A simple monochrome Jekyll blog"
baseurl: ""
url: ""

markdown: kramdown
theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - name: "Home"
    link: "/"
  - name: "Blog"
    link: "/blog"
  - name: "About"
    link: "/about"

giscus:
  repo: ""
  repo_id: ""
  category: ""
  category_id: ""
